### ISSUE TITLE
http://certifi.io/ down

### ISSUE THREAD

**Issue by nikokio** [certifi/certifi.io#15] opened 2017-10-19 13:40 UTC
Hello,

For several weeks now, the website http://certifi.io/ is down (at least, unreachable from France, Japan and Singapore)

No HTTP server seems to run:

```
Starting Nmap 7.01 ( https://nmap.org ) at 2017-10-19 15:33 CEST
Nmap scan report for certifi.io (174.138.57.24)
Host is up (0.072s latency).
Not shown: 998 closed ports
PORT    STATE    SERVICE
22/tcp  open     ssh
445/tcp filtered microsoft-ds

Nmap done: 1 IP address (1 host up) scanned in 265.40 seconds
```

Thanks
Regards

**Comment by Lukasa** [comment] 2017-10-20 00:45
Duplicate of #12.

**Closed by Lukasa** 2017-10-20 00:45 UTC

**Comment by nikokio** [comment] 2017-10-20 05:02
Hello,

I don't understand, #12 says "it fixed" but it's not... Pypi still refers to certifi.io and the site is still down

Thanks
